2023-04-22 14:06:11.511 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-22 14:06:12.213 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-22 14:07:28.544 WARNING (MainThread) [homeassistant.setup] Setup of image_upload is taking over 10 seconds.
2023-04-22 14:07:29.869 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-04-22 14:07:45.298 WARNING (MainThread) [homeassistant.setup] Setup of recorder is taking over 10 seconds.
2023-04-22 14:07:55.481 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2023-04-22 14:08:03.594 WARNING (MainThread) [homeassistant.setup] Setup of bluetooth is taking over 10 seconds.
2023-04-22 14:08:10.074 WARNING (MainThread) [homeassistant.components.systemmonitor.sensor] Cannot read CPU / processor temperature information
2023-04-22 14:08:15.093 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Samsung C48x Series (SEC30CDA7AC8DD0)' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2023-04-22 14:08:20.723 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for hacs using this method at custom_components/hacs/__init__.py, line 171: hass.config_entries.async_setup_platforms(
2023-04-22 20:48:47.342 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.100168336c_1 or it is/they are currently not available
2023-04-22 20:56:30.955 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-73736' coro=<async_install() running at /usr/src/homeassistant/homeassistant/components/update/__init__.py:156> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove(), Task.task_wakeup()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2023-04-22 20:56:31.029 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-73807' coro=<ServiceRegistry._run_service_in_background.<locals>.catch_exceptions() running at /usr/src/homeassistant/homeassistant/core.py:1838> wait_for=<Task pending name='Task-73734' coro=<ServiceRegistry._execute_service() running at /usr/src/homeassistant/homeassistant/core.py:1857> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove(), Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
